mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}


portal:
    image: hpcal1/ucscstudentportal:0.1 
    container_name: student-portal
    ports:
        - 4000:4000
    environment:
        - MYSQL_HOST=${MYSQL_HOST}
    links:
        - mysql
